name: shopping_app_prototype
description: A Shopping App prototype.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  best_buy_api:
    path: packages/best_buy_api
  animations: ^1.1.2
  built_collection: ^4.3.2
  cached_network_image: ^2.5.0
  flutter_bloc: ^6.1.1
  flutter_cache_manager: ^2.1.0
  freezed_annotation: ^0.12.0
  hydrated_bloc: ^6.1.0
  path_provider: ^1.6.24
  pedantic: ^1.9.2
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.10.11
  freezed: ^0.12.6
  json_serializable: ^3.5.1
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
