name: best_buy_api
description: A Best Buy API Client.
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  meta: ^1.2.4
  pedantic: ^1.9.2

dev_dependencies:
  build_runner: ^1.10.11
  freezed: ^0.12.6
  json_serializable: ^3.5.1
  mockito: ^4.1.3
  test: ^1.15.7
