name: best_buy_api
description: A Best Buy API Client.
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
